apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: synced-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: demo/external-secret
        property: username
    - secretKey: password
      remoteRef:
        key: demo/external-secret
        property: password
